set_property PACKAGE_PIN F9 [get_ports clk]
set_property PACKAGE_PIN H10 [get_ports {shift_low_out[0]}]
set_property PACKAGE_PIN H9 [get_ports {shift_low_out[1]}]
set_property PACKAGE_PIN G10 [get_ports {shift_low_out[2]}]
set_property PACKAGE_PIN F10 [get_ports {shift_low_out[3]}]
set_property PACKAGE_PIN H11 [get_ports {shift_high_out[0]}]
set_property PACKAGE_PIN G11 [get_ports {shift_high_out[1]}]
set_property PACKAGE_PIN G12 [get_ports {shift_high_out[2]}]
set_property PACKAGE_PIN F12 [get_ports {shift_high_out[3]}]
set_property PACKAGE_PIN E10 [get_ports rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_low_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_low_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_low_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_low_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_high_out[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_high_out[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_high_out[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {shift_high_out[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]

